"""Application settings plus the admin credential record they carry.

Mirrors ``server/settings.js`` field for field, so one ``appsettings.json``
works under either runtime.
"""

import math
import os
import re
import secrets
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse

from . import schema, tickets as ticket_store
from .auth import hash_password
from .paths import SETTINGS_PATH, SETTINGS_SAMPLE_PATH
from .store import read_json, write_json

DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_PASSWORD = "pickora"

BOARD_ALIGNMENTS = ("left", "center", "right")
DIRECTIONS = ("ltr", "rtl")
LOGO_POSITIONS = (
    "top-left",
    "top-center",
    "top-right",
    "bottom-left",
    "bottom-center",
    "bottom-right",
    "hidden",
)
BACKGROUND_FITS = ("cover", "contain", "fill", "tile")
DUPLICATE_POLICIES = ("skip", "allow")

# The placeholder Pickora identity bundled with the application, used until an
# organiser uploads their own. Both files are generated by
# tools/make-default-artwork.py.
DEFAULT_LOGO = "pickora-logo.png"
DEFAULT_BACKGROUND = "pickora-background.jpg"

# Artwork that once shipped as the default and now lives under archive/. A
# settings file written before the change still names it, so it is remapped
# instead of resolving to a file the server no longer serves.
RETIRED_ASSETS = {
    "Background.png": DEFAULT_BACKGROUND,
    "logo.jpg": DEFAULT_LOGO,
}

# NEW: how the winner reveal celebrates. "classic" is what the board has always
# done, so an event saved before this existed keeps its behaviour.
CELEBRATION_TYPES = (
    "classic",
    "streamers",
    "stars",
    "balloons",
    "snow",
    "money",
    "mix",
    "none",
)

# NEW: the social channels an organiser can publish, and how their QR codes are
# drawn and placed. "custom" carries its own label.
CHANNEL_TYPES = (
    "instagram",
    "facebook",
    "x",
    "youtube",
    "tiktok",
    "linkedin",
    "whatsapp",
    "telegram",
    "discord",
    "website",
    "custom",
)
QR_STYLES = ("standard", "colored", "logo", "rounded")
QR_POSITIONS = (
    "bottom-left",
    "bottom-right",
    "bottom-center",
    "top-right",
    "sidebar",
    "footer",
)
QR_SIZES = ("small", "medium", "large", "xl")
QR_DISPLAY_MODES = ("icons", "qr", "both")

# NEW: how the words on each screen are set. Every family here is either one the
# application already ships or a stack the operating system provides, so nothing
# needs fetching and an offline board looks the same as a hosted one.
FONT_FAMILIES = ("display", "body", "mono", "system", "sans", "serif")
# Zero is "leave the screen's own weight alone"; the rest are the weights the
# bundled faces actually carry.
FONT_WEIGHTS = (0, 300, 400, 500, 600, 700, 800)

# NEW: the plate drawn behind the words, so they stay readable over artwork.
BACKDROP_RADII = ("none", "slight", "rounded", "pill")
BACKDROP_PADDINGS = ("none", "small", "medium", "large")
TEXT_ALIGNMENTS = ("auto", "left", "center", "right")

# NEW: what the board does with a prize that has more than one photograph.
PRIZE_IMAGE_MODES = ("single", "carousel")
CAROUSEL_TRANSITIONS = ("fade", "slide")
PRIZE_IMAGE_SHAPES = ("rounded", "circle", "oval")
MAX_CHANNELS = 24

# Which end of the prize list the evening starts from.
PRIZE_DRAW_ORDERS = ("highest-first", "lowest-first")

# Whether the prize is named before its draw, or held back until the winner.
PRIZE_ANNOUNCE_MODES = ("before", "after")
WELCOME_PLACEMENTS = ("overlay", "panel")

MAX_WELCOME_IMAGES = 20
MAX_PRIZES = 20
MAX_PRIZE_IMAGES = 12

ORDINALS = (
    "First prize", "Second prize", "Third prize", "Fourth prize", "Fifth prize",
    "Sixth prize", "Seventh prize", "Eighth prize", "Ninth prize", "Tenth prize",
)

PRIZE_ID = re.compile(r"^[a-z0-9-]{1,40}$")
WELCOME_INTERVAL_LIMITS = (1500, 60000)

# Used only when there is no configuration and no participant file to learn
# from — deliberately event-neutral.
DEFAULT_FIELDS = [
    {"key": "ticket", "label": "Ticket", "sensitive": False},
    {"key": "name", "label": "Name", "sensitive": False},
    {"key": "details", "label": "Details", "sensitive": False},
    {"key": "contact", "label": "Contact", "sensitive": True},
]

DEFAULT_CONFETTI_PALETTE = ["#ffd54f", "#ff8a65", "#4dd0e1", "#f06292", "#aed581", "#ffffff"]

DEFAULT_COPY = {
    "readyTitle": "Ready to draw",
    "readyDetail": "Press Start",
    "winnerEyebrow": "Winner",
    "prizeLabel": "Prize",
    "lastWinnerEyebrow": "Last winner",
    "completeTitle": "All prizes awarded",
    "startButton": "Start",
    "stopButton": "Stop",
    "winnersHeading": "Winners",
    "winnersEmpty": "No draws yet.",
    "winnersToggle": "Winners",
    "fullscreenButton": "Fullscreen",
    "organiserLink": "Organiser",
    "welcomeToggle": "Welcome",
    "boardToggle": "Draw board",
    "prizesToggle": "Prizes",
    "upNextLabel": "Up next",
    "drawPrompt": "Press Start to draw",
    "prizesBack": "Back to the draw",
    "newDrawButton": "New draw",
    "newDrawConfirm": "Clear the current draw and start over?",
    "footer": "Pickora · by Shenu",
    "loading": "Preparing the draw…",
}

CLAMPS = {
    "totalPrizes": (1, 10000),
    "rollingSpeed": (10, 1000),
    "confettiDuration": (0, 60000),
    "confettiCount": (0, 600),
    # Up to half a minute: long enough to hold a room in suspense, and zero is
    # a real choice meaning "no announcement at all".
    "winnerAnnouncementDelay": (0, 30000),
    "confettiStartDelay": (0, 15000),
    "minimumRollMs": (0, 30000),
    "logoMaxHeight": (24, 480),
    "overlayOpacity": (0, 100),
    # NEW: the board's own measurements. Zero everywhere means "leave it to the
    # stylesheet", which is what every board did before these existed, so an
    # organiser only sets the one thing they actually want to change.
    "textFontSize": (0, 200),
    "textOpacity": (0, 100),
    "textLineHeight": (0, 300),
    "textLetterSpacing": (-20, 100),
    "textBackdropOpacity": (0, 100),
    "prizeSlideMs": (1000, 20000),
    "reelWidth": (0, 2400),
    "reelHeight": (0, 420),
    "reelFontSize": (0, 220),
    "controlMinWidth": (0, 420),
    "controlHeight": (0, 120),
    "controlFontSize": (0, 48),
    "controlPaddingX": (0, 90),
    "controlRadius": (0, 999),
    "welcomeIntervalMs": WELCOME_INTERVAL_LIMITS,
    "prizeIntervalMs": WELCOME_INTERVAL_LIMITS,
}

ASSET_PATH = re.compile(r"^assets/[A-Za-z0-9._-]+$")
BARE_IMAGE = re.compile(r"^[A-Za-z0-9._-]+\.(png|jpe?g|gif|webp|svg)$", re.I)
HEX_COLOR = re.compile(r"^#[0-9a-f]{3,8}$", re.I)


def _clamp(key: str, value: Any, fallback: int) -> int:
    # A list converts to neither backend's idea of a number, but float() accepts
    # a few shapes Number() does not; both are refused here so the two agree.
    if isinstance(value, (list, dict)) or value is None:
        return fallback
    try:
        number = float(value)
    except (TypeError, ValueError):
        return fallback
    if number != number or number in (float("inf"), float("-inf")):
        return fallback
    low, high = CLAMPS[key]
    # FIX: Python rounds a half to even (2.5 -> 2) and JavaScript rounds it up
    # (2.5 -> 3). Floor of value-plus-a-half is what Math.round does, including
    # for negatives, so a hostile half-value lands on the same integer in both.
    return int(min(high, max(low, math.floor(number + 0.5))))


def _as_bool(value: Any, fallback: bool) -> bool:
    if isinstance(value, bool):
        return value
    if value == "true":
        return True
    if value == "false":
        return False
    return fallback


def _as_choice(value: Any, choices: tuple, fallback: str) -> str:
    return value if value in choices else fallback


def _as_text(value: Any, fallback: str, max_length: int = 200) -> str:
    if not isinstance(value, str):
        return fallback
    trimmed = value.strip()
    return trimmed[:max_length] if trimmed else fallback


def _as_asset_path(value: Any) -> str:
    if not isinstance(value, str):
        return ""
    trimmed = value.strip()
    return trimmed if ASSET_PATH.match(trimmed) or BARE_IMAGE.match(trimmed) else ""


def _branding_asset(value: Any, fallback: str) -> str:
    """Resolve a branding image to something the board can actually load.

    An empty string is the organiser deliberately clearing the slot, so it is
    kept. Anything unreadable, or naming artwork that has since been retired to
    ``archive/``, falls back to the bundled Pickora default rather than leaving
    a broken image on the screen at the event.
    """
    if value == "":
        return ""
    resolved = _as_asset_path(value)
    if not resolved:
        return fallback
    return RETIRED_ASSETS.get(resolved, resolved)


def _as_sheet_url(value: Any) -> str:
    """A remembered Google Sheets export address.

    Only ever set from the address sheets.py built, so what is stored can be
    re-fetched without the organiser pasting the link again.
    """
    if not isinstance(value, str):
        return ""
    trimmed = value.strip()
    return trimmed[:500] if trimmed.startswith("https://docs.google.com/spreadsheets/") else ""


def _normalize_copy(raw: Any) -> Dict[str, str]:
    source = raw if isinstance(raw, dict) else {}
    return {key: _as_text(source.get(key), default, 160) for key, default in DEFAULT_COPY.items()}


def _normalize_palette(raw: Any) -> list:
    items = raw if isinstance(raw, list) else []
    colors = [c.strip() for c in items if isinstance(c, str) and HEX_COLOR.match(c.strip())][:12]
    return colors or list(DEFAULT_CONFETTI_PALETTE)


def ordinal_label(index: int) -> str:
    return ORDINALS[index] if index < len(ORDINALS) else f"Prize {index + 1}"


def _is_default_label(label: Any) -> bool:
    if not isinstance(label, str) or not label.strip():
        return True
    trimmed = label.strip()
    return trimmed in ORDINALS or bool(re.match(r"^Prize \d+$", trimmed))


def _normalize_images(raw: Any, limit: int) -> list:
    """Normalise a carousel image list, dropping anything unusable."""
    items = raw if isinstance(raw, list) else []
    images = []

    for entry in items:
        image = entry if isinstance(entry, dict) else {"src": entry}
        src = _as_asset_path(image.get("src"))
        if not src:
            continue

        def dimension(value: Any) -> Optional[int]:
            try:
                number = int(value)
            except (TypeError, ValueError):
                return None
            return number or None

        images.append(
            {
                "src": src,
                "caption": _as_text(image.get("caption"), "", 120),
                "width": dimension(image.get("width")),
                "height": dimension(image.get("height")),
            }
        )
        if len(images) >= limit:
            break

    return images


def _normalize_prizes(raw: Any) -> Dict[str, Any]:
    """The prize list. Order is rank: the first entry is first prize, and it is
    matched to a draw by position, so prize 1 goes with the first winner."""
    source = raw if isinstance(raw, dict) else {}
    items_raw = source.get("items") if isinstance(source.get("items"), list) else []

    items = []
    for index, entry in enumerate(items_raw):
        item = entry if isinstance(entry, dict) else {}
        name = _as_text(item.get("name"), "", 140)
        if not name:
            continue

        candidate = item.get("id")
        identifier = candidate if isinstance(candidate, str) and PRIZE_ID.match(candidate) else f"prize-{index + 1}"

        items.append(
            {
                "id": identifier,
                # A default label follows the position, so reordering renumbers
                # it. A label the organiser actually wrote is kept.
                "label": ordinal_label(index)
                if _is_default_label(item.get("label"))
                else _as_text(item.get("label"), ordinal_label(index), 60),
                "name": name,
                "description": _as_text(item.get("description"), "", 600),
                "images": _normalize_images(item.get("images"), MAX_PRIZE_IMAGES),
            }
        )
        if len(items) >= MAX_PRIZES:
            break

    # Ids must stay unique; a duplicate would make image uploads ambiguous.
    seen = set()
    unique = []
    for index, item in enumerate(items):
        if item["id"] in seen:
            item = {**item, "id": f"prize-{index + 1}-{secrets.token_hex(3)}"}
        seen.add(item["id"])
        unique.append(item)

    board = source.get("board") if isinstance(source.get("board"), dict) else {}

    return {
        # Ticked by default: the screen is part of the product, and an organiser
        # who does not want it in the board's navigation unticks it.
        "enabled": _as_bool(source.get("enabled"), True),
        "heading": _as_text(source.get("heading"), "Prizes", 120),
        "intro": _as_text(source.get("intro"), "", 400),
        "showOnWinner": _as_bool(source.get("showOnWinner"), True),
        "drawOrder": _as_choice(source.get("drawOrder"), PRIZE_DRAW_ORDERS, "highest-first"),
        "announceMode": _as_choice(source.get("announceMode"), PRIZE_ANNOUNCE_MODES, "before"),
        "showCaptions": _as_bool(source.get("showCaptions"), True),
        "intervalMs": _clamp("prizeIntervalMs", source.get("intervalMs"), 5000),
        # NEW: what the board does with a prize that has several photographs —
        # one still, or all of them turning.
        "board": {
            "imageMode": _as_choice(board.get("imageMode"), PRIZE_IMAGE_MODES, "single"),
            "autoplay": _as_bool(board.get("autoplay"), True),
            "slideMs": _clamp("prizeSlideMs", board.get("slideMs"), 3000),
            "transition": _as_choice(board.get("transition"), CAROUSEL_TRANSITIONS, "fade"),
            "showDots": _as_bool(board.get("showDots"), True),
            "shape": _as_choice(board.get("shape"), PRIZE_IMAGE_SHAPES, "rounded"),
        },
        "items": unique,
    }


def _normalize_welcome(raw: Any) -> Dict[str, Any]:
    """The guest welcome: a message plus a carousel of portraits, shown to
    greet a special guest before or between draws."""
    source = raw if isinstance(raw, dict) else {}
    images = _normalize_images(source.get("images"), MAX_WELCOME_IMAGES)

    return {
        # Ticked by default, as for the prize screen.
        "enabled": _as_bool(source.get("enabled"), True),
        "showOnLoad": _as_bool(source.get("showOnLoad"), True),
        "placement": _as_choice(source.get("placement"), WELCOME_PLACEMENTS, "overlay"),
        "title": _as_text(source.get("title"), "Our special guest", 120),
        "message": _as_text(source.get("message"), "", 400),
        "showCaptions": _as_bool(source.get("showCaptions"), True),
        "intervalMs": _clamp("welcomeIntervalMs", source.get("intervalMs"), 5000),
        "images": images,
    }


CHANNEL_ID = re.compile(r"^[a-z0-9-]{1,40}$")
URL_SCHEME = re.compile(r"^[a-z][a-z0-9+.-]*:", re.IGNORECASE)


def _as_link_url(value: Any) -> str:
    """NEW: a link an organiser wants the room to be able to reach.

    Only http(s) is allowed through: a QR code is scanned without being read,
    so anything that could hand the scanner a ``javascript:`` or ``data:`` URL
    has no business here.
    """
    if not isinstance(value, str):
        return ""
    trimmed = value.strip()
    if not trimmed:
        return ""

    candidate = trimmed if URL_SCHEME.match(trimmed) else f"https://{trimmed}"
    parsed = urlparse(candidate)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        return ""
    return candidate[:500]


def _normalize_channels(raw: Any) -> List[Dict[str, Any]]:
    """NEW: the organiser's social channels, in the order they arranged them."""
    entries = raw if isinstance(raw, list) else []
    channels: List[Dict[str, Any]] = []
    seen = set()

    for index, entry in enumerate(entries):
        item = entry if isinstance(entry, dict) else {}
        url = _as_link_url(item.get("url"))
        if not url:
            continue

        raw_id = item.get("id")
        identifier = raw_id if isinstance(raw_id, str) and CHANNEL_ID.match(raw_id) else f"channel-{index + 1}"
        if identifier in seen:
            continue
        seen.add(identifier)

        channels.append(
            {
                "id": identifier,
                "type": _as_choice(item.get("type"), CHANNEL_TYPES, "website"),
                "url": url,
                # A custom channel needs its own name; the rest fall back to
                # the channel's own, which the page supplies.
                "label": _as_text(item.get("label"), "", 40),
            }
        )

    return channels[:MAX_CHANNELS]


def _normalize_social(raw: Any) -> Dict[str, Any]:
    """NEW: how the channel block is drawn, and where it sits on every page."""
    source = raw if isinstance(raw, dict) else {}
    qr = source.get("qr") if isinstance(source.get("qr"), dict) else {}

    return {
        "heading": _as_text(source.get("heading"), "Follow the event", 60),
        "channels": _normalize_channels(source.get("channels")),
        "qr": {
            "style": _as_choice(qr.get("style"), QR_STYLES, "standard"),
            "position": _as_choice(qr.get("position"), QR_POSITIONS, "bottom-right"),
            "size": _as_choice(qr.get("size"), QR_SIZES, "medium"),
            "display": _as_choice(qr.get("display"), QR_DISPLAY_MODES, "both"),
            # Used by the "colored" style when the organiser wants one colour
            # rather than each channel's own.
            "color": _as_text(qr.get("color"), "", 40),
        },
    }


def _as_color(value: Any, fallback: str) -> str:
    """NEW: a hex colour, or empty for "whatever the screen already uses"."""
    if not isinstance(value, str):
        return fallback
    trimmed = value.strip()
    return trimmed if HEX_COLOR.match(trimmed) else fallback


def _normalize_text_style(raw: Any) -> Dict[str, Any]:
    """NEW: one screen's text style.

    Zero means "as the screen has it", so a style nobody has touched renders
    exactly as it did before any of this existed and an operator only sets the
    one thing they want to change.
    """
    source = raw if isinstance(raw, dict) else {}

    try:
        weight = int(source.get("fontWeight"))
    except (TypeError, ValueError):
        weight = 0

    backdrop = source.get("backdrop") if isinstance(source.get("backdrop"), dict) else {}

    return {
        "fontSize": _clamp("textFontSize", source.get("fontSize"), 0),
        "color": _as_color(source.get("color"), ""),
        "opacity": _clamp("textOpacity", source.get("opacity"), 100),
        "fontFamily": _as_choice(source.get("fontFamily"), FONT_FAMILIES, "body"),
        "fontWeight": weight if weight in FONT_WEIGHTS else 0,
        "align": _as_choice(source.get("align"), TEXT_ALIGNMENTS, "auto"),
        "lineHeight": _clamp("textLineHeight", source.get("lineHeight"), 0),
        "letterSpacing": _clamp("textLetterSpacing", source.get("letterSpacing"), 0),
        # NEW: opacity zero is no plate at all, which is the default, so a
        # screen nobody has configured is drawn exactly as it always was.
        "backdrop": {
            "color": _as_color(backdrop.get("color"), "#000000"),
            "opacity": _clamp("textBackdropOpacity", backdrop.get("opacity"), 0),
            "radius": _as_choice(backdrop.get("radius"), BACKDROP_RADII, "rounded"),
            "padding": _as_choice(backdrop.get("padding"), BACKDROP_PADDINGS, "medium"),
        },
    }


def _normalize_branding(raw: Any) -> Dict[str, Any]:
    source = raw if isinstance(raw, dict) else {}
    logo = source.get("logo") or {}
    background = source.get("background") or {}

    def dimension(value: Any) -> Optional[int]:
        try:
            number = int(value)
        except (TypeError, ValueError):
            return None
        return number or None

    return {
        "logo": {
            "src": _branding_asset(logo.get("src"), DEFAULT_LOGO),
            "position": _as_choice(logo.get("position"), LOGO_POSITIONS, "top-left"),
            "maxHeight": _clamp("logoMaxHeight", logo.get("maxHeight"), 96),
            "width": dimension(logo.get("width")),
            "height": dimension(logo.get("height")),
        },
        "background": {
            "src": _branding_asset(background.get("src"), DEFAULT_BACKGROUND),
            "fit": _as_choice(background.get("fit"), BACKGROUND_FITS, "cover"),
            "overlayOpacity": _clamp("overlayOpacity", background.get("overlayOpacity"), 45),
            "width": dimension(background.get("width")),
            "height": dimension(background.get("height")),
        },
    }


def _normalize_data(raw: Any, legacy_display: Dict[str, Any]) -> Dict[str, Any]:
    """Rebuild the participant schema.

    With no ``data`` block configured — a fresh install, or a file written
    before the schema existed — the columns are read from the participant file
    itself rather than assuming any particular event's shape.
    """
    source = raw if isinstance(raw, dict) else {}
    policy = _as_choice(source.get("duplicatePolicy"), DUPLICATE_POLICIES, "skip")
    # Where the list last came from, so a linked sheet can be pulled again.
    provenance = {
        "sourceUrl": _as_sheet_url(source.get("sourceUrl")),
        "sourceSyncedAt": _as_text(source.get("sourceSyncedAt"), "", 40),
    }
    fields = schema.normalize_fields(source.get("fields"))

    if fields:
        return {
            "identifier": schema.pick_identifier(fields, source.get("identifier")),
            "fields": fields,
            "duplicatePolicy": policy,
            **provenance,
        }

    inferred = ticket_store.infer_schema_from_file()
    if inferred:
        # A board that previously displayed contact details keeps doing so.
        adjusted = (
            [{**field, "sensitive": False} for field in inferred["fields"]]
            if legacy_display.get("showMobileInWinner") is True
            else inferred["fields"]
        )
        return {
            "identifier": inferred["identifier"],
            "fields": adjusted,
            "duplicatePolicy": policy,
            **provenance,
        }

    return {
        "identifier": DEFAULT_FIELDS[0]["key"],
        "fields": schema.normalize_fields(DEFAULT_FIELDS),
        "duplicatePolicy": policy,
        **provenance,
    }


def normalize_app_settings(raw: Any) -> Dict[str, Any]:
    source = raw if isinstance(raw, dict) else {}
    animation = source.get("animation") or {}
    ui = source.get("ui") or {}
    draw = source.get("draw") or {}
    display_source = source.get("display") or {}

    data = _normalize_data(source.get("data"), display_source)
    display = schema.normalize_display(display_source, data)
    display["autoStopWhenPrizesExhausted"] = _as_bool(display_source.get("autoStopWhenPrizesExhausted"), True)

    return {
        "totalPrizes": _clamp("totalPrizes", source.get("totalPrizes"), 10),
        "eventName": _as_text(source.get("eventName"), "Pickora", 120),
        "organizationName": _as_text(source.get("organizationName"), "", 120),
        "locale": _as_text(source.get("locale"), "en", 20),
        "direction": _as_choice(source.get("direction"), DIRECTIONS, "ltr"),
        "data": data,
        "display": display,
        "animation": {
            "rollingSpeed": _clamp("rollingSpeed", animation.get("rollingSpeed"), 60),
            "confettiDuration": _clamp("confettiDuration", animation.get("confettiDuration"), 8000),
            "confettiCount": _clamp("confettiCount", animation.get("confettiCount"), 150),
            "confettiPalette": _normalize_palette(animation.get("confettiPalette")),
            "winnerAnnouncementDelay": _clamp("winnerAnnouncementDelay", animation.get("winnerAnnouncementDelay"), 5000),
            "confettiStartDelay": _clamp("confettiStartDelay", animation.get("confettiStartDelay"), 500),
            # NEW: which celebration the reveal fires. Absent on an event saved
            # before this existed, which is exactly what "classic" means.
            "celebration": _as_choice(animation.get("celebration"), CELEBRATION_TYPES, "classic"),
        },
        "draw": {
            "publicDrawEnabled": _as_bool(draw.get("publicDrawEnabled"), True),
            "requireAuthForDraw": _as_bool(draw.get("requireAuthForDraw"), False),
            "allowResetFromBoard": _as_bool(draw.get("allowResetFromBoard"), False),
            "minimumRollMs": _clamp("minimumRollMs", draw.get("minimumRollMs"), 1200),
        },
        "branding": _normalize_branding(source.get("branding")),
        "social": _normalize_social(source.get("social")),
        # NEW: each screen's words are styled on their own; none of the three
        # share a setting with another.
        "text": {
            "welcome": _normalize_text_style((source.get("text") or {}).get("welcome")),
            "prizes": _normalize_text_style((source.get("text") or {}).get("prizes")),
            "board": _normalize_text_style((source.get("text") or {}).get("board")),
        },
        "welcome": _normalize_welcome(source.get("welcome")),
        "prizes": _normalize_prizes(source.get("prizes")),
        "copy": _normalize_copy(source.get("copy")),
        "ui": {
            # NEW: sizes for the two things the room looks at. Zero is "as the
            # stylesheet has it", which keeps every existing board as it is.
            "reel": {
                "width": _clamp("reelWidth", (ui.get("reel") or {}).get("width"), 0),
                "height": _clamp("reelHeight", (ui.get("reel") or {}).get("height"), 0),
                "fontSize": _clamp("reelFontSize", (ui.get("reel") or {}).get("fontSize"), 0),
            },
            "controls": {
                "minWidth": _clamp("controlMinWidth", (ui.get("controls") or {}).get("minWidth"), 0),
                "height": _clamp("controlHeight", (ui.get("controls") or {}).get("height"), 0),
                "fontSize": _clamp("controlFontSize", (ui.get("controls") or {}).get("fontSize"), 0),
                "paddingX": _clamp("controlPaddingX", (ui.get("controls") or {}).get("paddingX"), 0),
                # Unlike the rest, a radius has a real default: zero is a
                # square corner, which is a choice, not "leave it alone".
                "radius": _clamp("controlRadius", (ui.get("controls") or {}).get("radius"), 999),
            },
            "primaryColor": _as_text(ui.get("primaryColor"), "#ffeb3b", 40),
            "backgroundColor": _as_text(
                ui.get("backgroundColor"), "radial-gradient(circle at top, #1d2671, #c33764)", 400
            ),
            # NEW: on by default, so a board configured before this existed
            # keeps showing the event name exactly as it did.
            "showEventName": _as_bool(ui.get("showEventName"), True),
            # NEW: whether the board offers "New draw" at all. On by default,
            # for the same reason. Who may *use* it is draw.allowResetFromBoard.
            "showNewDrawButton": _as_bool(ui.get("showNewDrawButton"), True),
            "showOrganizationName": _as_bool(ui.get("showOrganizationName"), True),
            "showWinnersPanel": _as_bool(ui.get("showWinnersPanel"), False),
            "showStats": _as_bool(ui.get("showStats"), False),
            "boardAlignment": _as_choice(ui.get("boardAlignment"), BOARD_ALIGNMENTS, "center"),
        },
    }


def load_settings_file() -> Dict[str, Any]:
    source = SETTINGS_PATH if SETTINGS_PATH.exists() else SETTINGS_SAMPLE_PATH
    raw = read_json(source, {"appSettings": {}}) or {}
    return {"appSettings": normalize_app_settings(raw.get("appSettings")), "adminAuth": raw.get("adminAuth")}


def save_settings_file(settings_file: Dict[str, Any]) -> None:
    write_json(
        SETTINGS_PATH,
        {"appSettings": settings_file["appSettings"], "adminAuth": settings_file.get("adminAuth")},
    )


def ensure_admin_credentials() -> Dict[str, Any]:
    """Return the credential record, bootstrapping it on first run.

    ``ADMIN_USERNAME``/``ADMIN_PASSWORD`` win over the file when both are set,
    so a deployment can override whatever is committed.
    """
    settings_file = load_settings_file()
    env_username = os.environ.get("ADMIN_USERNAME")
    env_password = os.environ.get("ADMIN_PASSWORD")

    if env_username and env_password:
        credential = hash_password(env_password)
        credential.update({"username": env_username, "source": "environment", "isDefaultPassword": False})
        return {"settingsFile": {**settings_file, "adminAuth": credential}, "created": False, "usingDefaults": False}

    existing = settings_file.get("adminAuth")
    if existing and existing.get("hash"):
        return {
            "settingsFile": settings_file,
            "created": False,
            "usingDefaults": bool(existing.get("isDefaultPassword")),
        }

    credential = hash_password(DEFAULT_ADMIN_PASSWORD)
    credential.update(
        {
            "username": DEFAULT_ADMIN_USERNAME,
            "source": "file",
            "isDefaultPassword": True,
            "updatedAt": datetime.now(timezone.utc).isoformat(),
        }
    )
    bootstrapped = {**settings_file, "adminAuth": credential}
    save_settings_file(bootstrapped)
    return {"settingsFile": bootstrapped, "created": True, "usingDefaults": True}
