'use strict';

const { PATHS } = require('./paths');
const { readJson, writeJson, readBundledJson } = require('./store');
const { hashPassword } = require('./auth');
const schema = require('./schema');
const ticketStore = require('./tickets');

const DEFAULT_ADMIN_USERNAME = 'admin';
const DEFAULT_ADMIN_PASSWORD = 'pickora';

const BOARD_ALIGNMENTS = Object.freeze(['left', 'center', 'right']);
const DIRECTIONS = Object.freeze(['ltr', 'rtl']);
const LOGO_POSITIONS = Object.freeze([
  'top-left',
  'top-center',
  'top-right',
  'bottom-left',
  'bottom-center',
  'bottom-right',
  'hidden',
]);
const BACKGROUND_FITS = Object.freeze(['cover', 'contain', 'fill', 'tile']);
const DUPLICATE_POLICIES = Object.freeze(['skip', 'allow']);

/* The placeholder Pickora identity bundled with the application, used until an
   organiser uploads their own. Both files are generated by
   tools/make-default-artwork.py. */
const DEFAULT_LOGO = 'pickora-logo.png';
const DEFAULT_BACKGROUND = 'pickora-background.jpg';

/* Artwork that once shipped as the default and now lives under archive/. A
   settings file written before the change still names it, so it is remapped
   instead of resolving to a file the server no longer serves. */
const RETIRED_ASSETS = new Map([
  ['Background.png', DEFAULT_BACKGROUND],
  ['logo.jpg', DEFAULT_LOGO],
]);

// NEW: how the winner reveal celebrates. 'classic' is what the board has
// always done, so an event saved before this existed keeps its behaviour.
const CELEBRATION_TYPES = Object.freeze([
  'classic',
  'streamers',
  'stars',
  'balloons',
  'snow',
  'money',
  'mix',
  'none',
]);

// NEW: the social channels an organiser can publish, and how their QR codes
// are drawn and placed. 'custom' carries its own label.
const CHANNEL_TYPES = Object.freeze([
  'instagram',
  'facebook',
  'x',
  'youtube',
  'tiktok',
  'linkedin',
  'whatsapp',
  'telegram',
  'discord',
  'website',
  'custom',
]);
const QR_STYLES = Object.freeze(['standard', 'colored', 'logo', 'rounded']);
const QR_POSITIONS = Object.freeze([
  'bottom-left',
  'bottom-right',
  'bottom-center',
  'top-right',
  'sidebar',
  'footer',
]);
const QR_SIZES = Object.freeze(['small', 'medium', 'large', 'xl']);
const QR_DISPLAY_MODES = Object.freeze(['icons', 'qr', 'both']);

/* NEW: how the words on each screen are set. Every family here is either one
   the application already ships or a stack the operating system provides, so
   nothing needs fetching and an offline board looks the same as a hosted one. */
const FONT_FAMILIES = Object.freeze(['display', 'body', 'mono', 'system', 'sans', 'serif']);
// Zero is "leave the screen's own weight alone"; the rest are the weights the
// bundled faces actually carry.
const FONT_WEIGHTS = Object.freeze([0, 300, 400, 500, 600, 700, 800]);

/* NEW: the plate drawn behind the words, so they stay readable over artwork. */
const BACKDROP_RADII = Object.freeze(['none', 'slight', 'rounded', 'pill']);
const BACKDROP_PADDINGS = Object.freeze(['none', 'small', 'medium', 'large']);
const TEXT_ALIGNMENTS = Object.freeze(['auto', 'left', 'center', 'right']);

/* NEW: what the board does with a prize that has more than one photograph. */
const PRIZE_IMAGE_MODES = Object.freeze(['single', 'carousel']);
const CAROUSEL_TRANSITIONS = Object.freeze(['fade', 'slide']);
const PRIZE_IMAGE_SHAPES = Object.freeze(['rounded', 'circle', 'oval']);
const MAX_CHANNELS = 24;

// Which end of the prize list the evening starts from.
const PRIZE_DRAW_ORDERS = Object.freeze(['highest-first', 'lowest-first']);

// Whether the prize is named before its draw, or held back until the winner.
const PRIZE_ANNOUNCE_MODES = Object.freeze(['before', 'after']);
const WELCOME_PLACEMENTS = Object.freeze(['overlay', 'panel']);

/* NEW: the shape a screen's photographs are cut to, and where they sit.
   Note these are the carousel's own placements — WELCOME_PLACEMENTS above is a
   different question entirely, about how the welcome screen itself is shown. */
const CAROUSEL_SHAPES = Object.freeze(['rectangle', 'rounded', 'square', 'oval', 'circle']);
const CAROUSEL_ASPECTS = Object.freeze(['standard', 'wide', 'classic']);
const CAROUSEL_PLACEMENTS = Object.freeze(['top', 'center', 'bottom', 'left', 'right']);

/**
 * One screen's carousel frame.
 *
 * The defaults are passed in rather than fixed, because they differ: the
 * welcome screen's photographs have been a circle below the message since it
 * was redesigned, and a prize's have been a plain frame above its name. Both
 * stay exactly as they are until an organiser says otherwise.
 */
function normalizeCarousel(input, defaults) {
  const source = input && typeof input === 'object' ? input : {};

  return {
    shape: asChoice(source.shape, CAROUSEL_SHAPES, defaults.shape),
    aspect: asChoice(source.aspect, CAROUSEL_ASPECTS, defaults.aspect),
    radius: clamp('carouselRadius', source.radius, defaults.radius),
    placement: asChoice(source.placement, CAROUSEL_PLACEMENTS, defaults.placement),
    // NEW: whether the dots under the photographs are there at all. On by
    // default, which is what both screens have always shown.
    showDots: asBoolean(source.showDots, defaults.showDots),
  };
}

const WELCOME_CAROUSEL_DEFAULTS = Object.freeze({
  shape: 'circle',
  aspect: 'standard',
  radius: 18,
  placement: 'bottom',
  showDots: true,
});

const PRIZE_CAROUSEL_DEFAULTS = Object.freeze({
  shape: 'rectangle',
  aspect: 'standard',
  radius: 18,
  placement: 'top',
  showDots: true,
});

const MAX_WELCOME_IMAGES = 20;
const MAX_PRIZES = 20;
const MAX_PRIZE_IMAGES = 12;
const WELCOME_INTERVAL_LIMITS = Object.freeze([1500, 60000]);

// Used only when there is no configuration and no participant file to learn
// from — deliberately event-neutral.
const DEFAULT_FIELDS = Object.freeze([
  { key: 'ticket', label: 'Ticket', sensitive: false },
  { key: 'name', label: 'Name', sensitive: false },
  { key: 'details', label: 'Details', sensitive: false },
  { key: 'contact', label: 'Contact', sensitive: true },
]);

const DEFAULT_CONFETTI_PALETTE = Object.freeze(['#ffd54f', '#ff8a65', '#4dd0e1', '#f06292', '#aed581', '#ffffff']);

const DEFAULT_COPY = Object.freeze({
  readyTitle: 'Ready to draw',
  readyDetail: 'Press Start',
  winnerEyebrow: 'Winner',
  prizeLabel: 'Prize',
  lastWinnerEyebrow: 'Last winner',
  completeTitle: 'All prizes awarded',
  startButton: 'Start',
  stopButton: 'Stop',
  winnersHeading: 'Winners',
  winnersEmpty: 'No draws yet.',
  winnersToggle: 'Winners',
  fullscreenButton: 'Fullscreen',
  organiserLink: 'Organiser',
  welcomeToggle: 'Welcome',
  boardToggle: 'Draw board',
  prizesToggle: 'Prizes',
  upNextLabel: 'Up next',
  drawPrompt: 'Press Start to draw',
  prizesBack: 'Back to the draw',
  newDrawButton: 'New draw',
  newDrawConfirm: 'Clear the current draw and start over?',
  footer: 'Pickora · by Shenu',
  loading: 'Preparing the draw…',
});

const CLAMPS = Object.freeze({
  totalPrizes: [1, 10000],
  rollingSpeed: [10, 1000],
  confettiDuration: [0, 60000],
  confettiCount: [0, 600],
  // Up to half a minute: long enough to hold a room in suspense, and zero is
  // a real choice meaning "no announcement at all".
  winnerAnnouncementDelay: [0, 30000],
  confettiStartDelay: [0, 15000],
  minimumRollMs: [0, 30000],
  logoMaxHeight: [24, 480],
  overlayOpacity: [0, 100],
  /* NEW: the board's own measurements. Zero everywhere means "leave it to the
     stylesheet", which is what every board did before these existed, so an
     organiser only sets the one thing they actually want to change. */
  textFontSize: [0, 200],
  textOpacity: [0, 100],
  textLineHeight: [0, 300],
  textLetterSpacing: [-20, 100],
  textBackdropOpacity: [0, 100],
  carouselRadius: [0, 80],
  prizeSlideMs: [1000, 20000],
  reelWidth: [0, 2400],
  reelHeight: [0, 420],
  reelFontSize: [0, 220],
  controlMinWidth: [0, 420],
  controlHeight: [0, 120],
  controlFontSize: [0, 48],
  controlPaddingX: [0, 90],
  controlRadius: [0, 999],
  welcomeIntervalMs: WELCOME_INTERVAL_LIMITS,
  prizeIntervalMs: WELCOME_INTERVAL_LIMITS,
});

function clamp(key, value, fallback) {
  // FIX: Number() turns null, '' and [] into 0, where Python's float() refuses
  // them and falls back. The two backends have to agree, and for a setting like
  // the announcement delay the difference is not cosmetic — zero is a real
  // instruction ("no announcement"), so a missing value must never read as one.
  const numeric =
    typeof value === 'number' ||
    typeof value === 'boolean' ||
    (typeof value === 'string' && value.trim() !== '');
  if (!numeric) return fallback;

  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  const [min, max] = CLAMPS[key];
  return Math.min(max, Math.max(min, Math.round(number)));
}

function asBoolean(value, fallback) {
  if (typeof value === 'boolean') return value;
  if (value === 'true') return true;
  if (value === 'false') return false;
  return fallback;
}

function asChoice(value, choices, fallback) {
  return choices.includes(value) ? value : fallback;
}

function asText(value, fallback, maxLength = 200) {
  if (typeof value !== 'string') return fallback;
  const trimmed = value.trim();
  return trimmed ? trimmed.slice(0, maxLength) : fallback;
}

function asAssetPath(value) {
  if (typeof value !== 'string') return '';
  const trimmed = value.trim();
  const isSafe = /^assets\/[A-Za-z0-9._-]+$/.test(trimmed) || /^[A-Za-z0-9._-]+\.(png|jpe?g|gif|webp|svg)$/i.test(trimmed);
  return isSafe ? trimmed : '';
}

/**
 * Resolves a branding image to something the board can actually load.
 *
 * An empty string is the organiser deliberately clearing the slot, so it is
 * kept. Anything unreadable, or naming artwork that has since been retired to
 * archive/, falls back to the bundled Pickora default rather than leaving a
 * broken image on the screen at the event.
 */
function brandingAsset(value, fallback) {
  if (value === '') return '';
  const resolved = asAssetPath(value);
  if (!resolved) return fallback;
  return RETIRED_ASSETS.get(resolved) || resolved;
}

/**
 * A remembered Google Sheets export address.
 *
 * Only ever set from the address sheets.js built, so what is stored can be
 * re-fetched without the organiser pasting the link again.
 */
function asSheetUrl(value) {
  if (typeof value !== 'string') return '';
  const trimmed = value.trim();
  return /^https:\/\/docs\.google\.com\/spreadsheets\//.test(trimmed) ? trimmed.slice(0, 500) : '';
}

function normalizeCopy(input) {
  const source = input && typeof input === 'object' ? input : {};
  return Object.keys(DEFAULT_COPY).reduce(
    (accumulator, key) => ({ ...accumulator, [key]: asText(source[key], DEFAULT_COPY[key], 160) }),
    {}
  );
}

/** NEW: a hex colour, or empty for "whatever the screen already uses". */
function asColor(value, fallback) {
  if (typeof value !== 'string') return fallback;
  const trimmed = value.trim();
  return /^#[0-9a-f]{3,8}$/i.test(trimmed) ? trimmed : fallback;
}

function normalizePalette(input) {
  const list = Array.isArray(input) ? input : [];
  const colors = list
    .filter((color) => typeof color === 'string' && /^#[0-9a-f]{3,8}$/i.test(color.trim()))
    .map((color) => color.trim())
    .slice(0, 12);

  return colors.length > 0 ? colors : [...DEFAULT_CONFETTI_PALETTE];
}

/** Normalises a carousel image list, dropping anything unusable. */
function normalizeImages(input, limit) {
  const raw = Array.isArray(input) ? input : [];

  return raw
    .map((image) => {
      const entry = image && typeof image === 'object' ? image : { src: image };
      const src = asAssetPath(entry.src);
      if (!src) return null;
      return {
        src,
        caption: asText(entry.caption, '', 120),
        width: Number(entry.width) || null,
        height: Number(entry.height) || null,
      };
    })
    .filter(Boolean)
    .slice(0, limit);
}

/**
 * The prize list. Order is rank: the first entry is first prize, and it is
 * matched to a draw by position, so prize 1 goes with the first winner.
 */
function normalizePrizes(input) {
  const source = input && typeof input === 'object' ? input : {};
  const raw = Array.isArray(source.items) ? source.items : [];

  const items = raw
    .map((item, index) => {
      const entry = item && typeof item === 'object' ? item : {};
      const name = asText(entry.name, '', 140);
      if (!name) return null;

      return {
        // `.test()` stringifies, so an absent id would match as "undefined".
        id: typeof entry.id === 'string' && /^[a-z0-9-]{1,40}$/.test(entry.id) ? entry.id : `prize-${index + 1}`,
        // A default label follows the position, so reordering renumbers it.
        // A label the organiser actually wrote — "Grand prize" — is kept.
        label: isDefaultLabel(entry.label) ? ordinalLabel(index) : asText(entry.label, ordinalLabel(index), 60),
        name,
        description: asText(entry.description, '', 600),
        images: normalizeImages(entry.images, MAX_PRIZE_IMAGES),
      };
    })
    .filter(Boolean)
    .slice(0, MAX_PRIZES);

  // Ids must stay unique; a duplicate would make image uploads ambiguous.
  const seen = new Set();
  const unique = items.map((item, index) => {
    if (!seen.has(item.id)) {
      seen.add(item.id);
      return item;
    }
    const replacement = `prize-${index + 1}-${Math.random().toString(36).slice(2, 7)}`;
    seen.add(replacement);
    return { ...item, id: replacement };
  });

  return {
    // Ticked by default: the screen is part of the product, and an organiser
    // who does not want it in the board's navigation unticks it.
    enabled: asBoolean(source.enabled, true),
    heading: asText(source.heading, 'Prizes', 120),
    intro: asText(source.intro, '', 400),
    showOnWinner: asBoolean(source.showOnWinner, true),
    drawOrder: asChoice(source.drawOrder, PRIZE_DRAW_ORDERS, 'highest-first'),
    announceMode: asChoice(source.announceMode, PRIZE_ANNOUNCE_MODES, 'before'),
    showCaptions: asBoolean(source.showCaptions, true),
    intervalMs: clamp('prizeIntervalMs', source.intervalMs, 5000),
    /* NEW: the frame a prize's photographs are cut to on the prize screen,
       and where they sit against its name. The board has its own, below. */
    carousel: normalizeCarousel(source.carousel, PRIZE_CAROUSEL_DEFAULTS),
    /* NEW: what the board does with a prize that has several photographs —
       one still, or all of them turning. */
    board: (() => {
      const board = source.board && typeof source.board === 'object' ? source.board : {};
      return {
        imageMode: asChoice(board.imageMode, PRIZE_IMAGE_MODES, 'single'),
        autoplay: asBoolean(board.autoplay, true),
        slideMs: clamp('prizeSlideMs', board.slideMs, 3000),
        transition: asChoice(board.transition, CAROUSEL_TRANSITIONS, 'fade'),
        showDots: asBoolean(board.showDots, true),
        shape: asChoice(board.shape, PRIZE_IMAGE_SHAPES, 'rounded'),
      };
    })(),
    items: unique,
  };
}

const ORDINALS = Object.freeze([
  'First prize', 'Second prize', 'Third prize', 'Fourth prize', 'Fifth prize',
  'Sixth prize', 'Seventh prize', 'Eighth prize', 'Ninth prize', 'Tenth prize',
]);

function ordinalLabel(index) {
  return ORDINALS[index] || `Prize ${index + 1}`;
}

function isDefaultLabel(label) {
  if (typeof label !== 'string' || !label.trim()) return true;
  const trimmed = label.trim();
  return ORDINALS.includes(trimmed) || /^Prize \d+$/.test(trimmed);
}

/**
 * The guest welcome: a message plus a carousel of portraits, shown to greet a
 * special guest before or between draws.
 */
function normalizeWelcome(input) {
  const source = input && typeof input === 'object' ? input : {};
  const images = normalizeImages(source.images, MAX_WELCOME_IMAGES);

  return {
    // Ticked by default, as for the prize screen.
    enabled: asBoolean(source.enabled, true),
    showOnLoad: asBoolean(source.showOnLoad, true),
    placement: asChoice(source.placement, WELCOME_PLACEMENTS, 'overlay'),
    title: asText(source.title, 'Our special guest', 120),
    message: asText(source.message, '', 400),
    showCaptions: asBoolean(source.showCaptions, true),
    intervalMs: clamp('welcomeIntervalMs', source.intervalMs, 5000),
    carousel: normalizeCarousel(source.carousel, WELCOME_CAROUSEL_DEFAULTS),
    images,
  };
}

/**
 * NEW: a link an organiser wants the room to be able to reach.
 *
 * Only http(s) is allowed through: a QR code is scanned without being read,
 * so anything that could hand the scanner a javascript: or data: URL has no
 * business here.
 */
function asLinkUrl(value) {
  if (typeof value !== 'string') return '';
  const trimmed = value.trim();
  if (!trimmed) return '';

  const candidate = /^[a-z][a-z0-9+.-]*:/i.test(trimmed) ? trimmed : `https://${trimmed}`;
  try {
    const parsed = new URL(candidate);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return '';
    if (!parsed.host) return '';
    // What the organiser typed, not the parser's rewrite of it: URL adds a
    // trailing slash to a bare origin, which the Python side does not, and a
    // settings file must not churn depending on which backend saved it.
    return candidate.slice(0, 500);
  } catch (_error) {
    return '';
  }
}

/** NEW: the organiser's social channels, in the order they arranged them. */
function normalizeChannels(input) {
  const raw = Array.isArray(input) ? input : [];
  const seen = new Set();

  return raw
    .map((entry, index) => {
      const item = entry && typeof entry === 'object' ? entry : {};
      const url = asLinkUrl(item.url);
      if (!url) return null;

      const type = asChoice(item.type, CHANNEL_TYPES, 'website');
      const id =
        typeof item.id === 'string' && /^[a-z0-9-]{1,40}$/.test(item.id) ? item.id : `channel-${index + 1}`;

      return {
        id,
        type,
        url,
        // A custom channel needs its own name; the rest fall back to the
        // channel's own, which the page supplies.
        label: asText(item.label, '', 40),
      };
    })
    .filter(Boolean)
    .filter((item) => {
      if (seen.has(item.id)) return false;
      seen.add(item.id);
      return true;
    })
    .slice(0, MAX_CHANNELS);
}

/** NEW: how the channel block is drawn, and where it sits on every page. */
function normalizeSocial(input) {
  const source = input && typeof input === 'object' ? input : {};
  const qr = source.qr && typeof source.qr === 'object' ? source.qr : {};

  return {
    heading: asText(source.heading, 'Follow the event', 60),
    channels: normalizeChannels(source.channels),
    qr: {
      style: asChoice(qr.style, QR_STYLES, 'standard'),
      position: asChoice(qr.position, QR_POSITIONS, 'bottom-right'),
      size: asChoice(qr.size, QR_SIZES, 'medium'),
      display: asChoice(qr.display, QR_DISPLAY_MODES, 'both'),
      // Used by the 'colored' style when the organiser wants one colour rather
      // than each channel's own.
      color: asText(qr.color, '', 40),
    },
  };
}

/**
 * NEW: one screen's text style.
 *
 * Zero means "as the screen has it", so a style nobody has touched renders
 * exactly as it did before any of this existed and an operator only sets the
 * one thing they want to change.
 */
function normalizeTextStyle(input) {
  const source = input && typeof input === 'object' ? input : {};

  return {
    fontSize: clamp('textFontSize', source.fontSize, 0),
    color: asColor(source.color, ''),
    opacity: clamp('textOpacity', source.opacity, 100),
    fontFamily: asChoice(source.fontFamily, FONT_FAMILIES, 'body'),
    fontWeight: FONT_WEIGHTS.includes(Number(source.fontWeight)) ? Number(source.fontWeight) : 0,
    align: asChoice(source.align, TEXT_ALIGNMENTS, 'auto'),
    lineHeight: clamp('textLineHeight', source.lineHeight, 0),
    letterSpacing: clamp('textLetterSpacing', source.letterSpacing, 0),
    // NEW: opacity zero is no plate at all, which is the default, so a screen
    // nobody has configured is drawn exactly as it always was.
    backdrop: (() => {
      const backdrop = source.backdrop && typeof source.backdrop === 'object' ? source.backdrop : {};
      return {
        color: asColor(backdrop.color, '#000000'),
        opacity: clamp('textBackdropOpacity', backdrop.opacity, 0),
        radius: asChoice(backdrop.radius, BACKDROP_RADII, 'rounded'),
        padding: asChoice(backdrop.padding, BACKDROP_PADDINGS, 'medium'),
      };
    })(),
  };
}

function normalizeBranding(input) {
  const source = input && typeof input === 'object' ? input : {};
  const logo = source.logo || {};
  const background = source.background || {};

  return {
    logo: {
      src: brandingAsset(logo.src, DEFAULT_LOGO),
      position: asChoice(logo.position, LOGO_POSITIONS, 'top-left'),
      maxHeight: clamp('logoMaxHeight', logo.maxHeight, 96),
      width: Number(logo.width) || null,
      height: Number(logo.height) || null,
    },
    background: {
      src: brandingAsset(background.src, DEFAULT_BACKGROUND),
      fit: asChoice(background.fit, BACKGROUND_FITS, 'cover'),
      overlayOpacity: clamp('overlayOpacity', background.overlayOpacity, 45),
      width: Number(background.width) || null,
      height: Number(background.height) || null,
    },
  };
}

/**
 * Rebuilds the participant schema.
 *
 * With no `data` block configured — a fresh install, or a file written before
 * the schema existed — the columns are read from the participant file itself
 * rather than assuming any particular event's shape.
 */
function normalizeData(input, legacyDisplay) {
  const source = input && typeof input === 'object' ? input : {};
  const duplicatePolicy = asChoice(source.duplicatePolicy, DUPLICATE_POLICIES, 'skip');
  // Where the list last came from, so a linked sheet can be pulled again.
  const sourceUrl = asSheetUrl(source.sourceUrl);
  const sourceSyncedAt = asText(source.sourceSyncedAt, '', 40);
  const provenance = { sourceUrl, sourceSyncedAt };
  const fields = schema.normalizeFields(source.fields);

  if (fields.length > 0) {
    return { identifier: schema.pickIdentifier(fields, source.identifier), fields, duplicatePolicy, ...provenance };
  }

  const inferred = ticketStore.inferSchemaFromFile();
  if (inferred) {
    // A board that previously displayed contact details keeps doing so.
    const adjusted =
      legacyDisplay.showMobileInWinner === true
        ? inferred.fields.map((field) => ({ ...field, sensitive: false }))
        : inferred.fields;
    return { identifier: inferred.identifier, fields: adjusted, duplicatePolicy, ...provenance };
  }

  return {
    identifier: DEFAULT_FIELDS[0].key,
    fields: schema.normalizeFields(DEFAULT_FIELDS),
    duplicatePolicy,
    ...provenance,
  };
}

function normalizeAppSettings(input) {
  const source = input && typeof input === 'object' ? input : {};
  const animation = source.animation || {};
  const ui = source.ui || {};
  const draw = source.draw || {};
  const displaySource = source.display || {};

  const data = normalizeData(source.data, displaySource);
  const display = schema.normalizeDisplay(displaySource, data);

  return {
    totalPrizes: clamp('totalPrizes', source.totalPrizes, 10),
    eventName: asText(source.eventName, 'Pickora', 120),
    organizationName: asText(source.organizationName, '', 120),
    locale: asText(source.locale, 'en', 20),
    direction: asChoice(source.direction, DIRECTIONS, 'ltr'),

    data,
    display: {
      ...display,
      autoStopWhenPrizesExhausted: asBoolean(displaySource.autoStopWhenPrizesExhausted, true),
    },

    animation: {
      rollingSpeed: clamp('rollingSpeed', animation.rollingSpeed, 60),
      confettiDuration: clamp('confettiDuration', animation.confettiDuration, 8000),
      confettiCount: clamp('confettiCount', animation.confettiCount, 150),
      confettiPalette: normalizePalette(animation.confettiPalette),
      winnerAnnouncementDelay: clamp('winnerAnnouncementDelay', animation.winnerAnnouncementDelay, 5000),
      confettiStartDelay: clamp('confettiStartDelay', animation.confettiStartDelay, 500),
      // NEW: which celebration the reveal fires. Absent on an event saved
      // before this existed, which is exactly what 'classic' means.
      celebration: asChoice(animation.celebration, CELEBRATION_TYPES, 'classic'),
    },

    draw: {
      publicDrawEnabled: asBoolean(draw.publicDrawEnabled, true),
      requireAuthForDraw: asBoolean(draw.requireAuthForDraw, false),
      allowResetFromBoard: asBoolean(draw.allowResetFromBoard, false),
      minimumRollMs: clamp('minimumRollMs', draw.minimumRollMs, 1200),
    },

    branding: normalizeBranding(source.branding),
    social: normalizeSocial(source.social),
    // NEW: each screen's words are styled on their own; none of the three
    // share a setting with another.
    text: {
      welcome: normalizeTextStyle((source.text || {}).welcome),
      prizes: normalizeTextStyle((source.text || {}).prizes),
      board: normalizeTextStyle((source.text || {}).board),
    },
    welcome: normalizeWelcome(source.welcome),
    prizes: normalizePrizes(source.prizes),
    copy: normalizeCopy(source.copy),

    ui: {
      // NEW: sizes for the two things the room looks at. Zero is "as the
      // stylesheet has it", which keeps every existing board exactly as it is.
      reel: {
        width: clamp('reelWidth', (ui.reel || {}).width, 0),
        height: clamp('reelHeight', (ui.reel || {}).height, 0),
        fontSize: clamp('reelFontSize', (ui.reel || {}).fontSize, 0),
      },
      controls: {
        minWidth: clamp('controlMinWidth', (ui.controls || {}).minWidth, 0),
        height: clamp('controlHeight', (ui.controls || {}).height, 0),
        fontSize: clamp('controlFontSize', (ui.controls || {}).fontSize, 0),
        paddingX: clamp('controlPaddingX', (ui.controls || {}).paddingX, 0),
        // Unlike the rest, a radius has a real default: zero is a square
        // corner, which is a choice, not "leave it alone".
        radius: clamp('controlRadius', (ui.controls || {}).radius, 999),
      },
      primaryColor: asText(ui.primaryColor, '#ffeb3b', 40),
      backgroundColor: asText(ui.backgroundColor, 'radial-gradient(circle at top, #1d2671, #c33764)', 400),
      // NEW: on by default, so a board configured before this existed keeps
      // showing the event name exactly as it did.
      showEventName: asBoolean(ui.showEventName, true),
      // NEW: whether the board offers "New draw" at all. On by default, for
      // the same reason. Who may *use* it is draw.allowResetFromBoard.
      showNewDrawButton: asBoolean(ui.showNewDrawButton, true),
      showOrganizationName: asBoolean(ui.showOrganizationName, true),
      showWinnersPanel: asBoolean(ui.showWinnersPanel, false),
      showStats: asBoolean(ui.showStats, false),
      boardAlignment: asChoice(ui.boardAlignment, BOARD_ALIGNMENTS, 'center'),
    },
  };
}

function loadSettingsFile() {
  // Nothing stored yet — a first run, or a fresh deployment — starts from the
  // sample that ships with the application.
  const raw = readJson(PATHS.settings, null) || readBundledJson(PATHS.settingsSample, { appSettings: {} });
  return { appSettings: normalizeAppSettings(raw.appSettings), adminAuth: raw.adminAuth || null };
}

function saveSettingsFile(settingsFile) {
  writeJson(PATHS.settings, { appSettings: settingsFile.appSettings, adminAuth: settingsFile.adminAuth });
}

// Credentials live alongside the settings. Environment variables win when
// present so a deployment can override whatever is committed.
function ensureAdminCredentials() {
  const settingsFile = loadSettingsFile();
  const envUsername = process.env.ADMIN_USERNAME;
  const envPassword = process.env.ADMIN_PASSWORD;

  if (envUsername && envPassword) {
    return {
      settingsFile: {
        ...settingsFile,
        adminAuth: { ...hashPassword(envPassword), username: envUsername, source: 'environment', isDefaultPassword: false },
      },
      created: false,
      usingDefaults: false,
    };
  }

  if (settingsFile.adminAuth && settingsFile.adminAuth.hash) {
    return { settingsFile, created: false, usingDefaults: Boolean(settingsFile.adminAuth.isDefaultPassword) };
  }

  const bootstrapped = {
    ...settingsFile,
    adminAuth: {
      ...hashPassword(DEFAULT_ADMIN_PASSWORD),
      username: DEFAULT_ADMIN_USERNAME,
      source: 'file',
      isDefaultPassword: true,
      updatedAt: new Date().toISOString(),
    },
  };

  saveSettingsFile(bootstrapped);
  return { settingsFile: bootstrapped, created: true, usingDefaults: true };
}

module.exports = {
  DEFAULT_ADMIN_USERNAME,
  DEFAULT_ADMIN_PASSWORD,
  DEFAULT_COPY,
  BOARD_ALIGNMENTS,
  DIRECTIONS,
  LOGO_POSITIONS,
  CELEBRATION_TYPES,
  CHANNEL_TYPES,
  QR_STYLES,
  QR_POSITIONS,
  QR_SIZES,
  QR_DISPLAY_MODES,
  MAX_CHANNELS,
  BACKGROUND_FITS,
  DUPLICATE_POLICIES,
  WELCOME_PLACEMENTS,
  MAX_WELCOME_IMAGES,
  MAX_PRIZES,
  MAX_PRIZE_IMAGES,
  PRIZE_DRAW_ORDERS,
  PRIZE_ANNOUNCE_MODES,
  ordinalLabel,
  normalizeAppSettings,
  loadSettingsFile,
  saveSettingsFile,
  ensureAdminCredentials,
};
